using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MiniHttpServer.Sharer
{
    public static class ContentType
    {
        private static readonly Dictionary<string, string> TypesExtesionsDict = new Dictionary<string, string>
        {
            { "html", "text/html; charset=utf-8" },
            { "htm", "text/html; charset=utf-8" },
            { "css", "text/css; charset=utf-8" },
            { "js", "application/javascript; charset=utf-8" },
            { "json", "application/json; charset=utf-8" },
            { "xml", "application/xml; charset=utf-8" },
            { "txt", "text/plain; charset=utf-8" },
            { "jpg", "image/jpeg" },
            { "jpeg", "image/jpeg" },
            { "png", "image/png" },
            { "gif", "image/gif" },
            { "svg", "image/svg+xml" },
            { "ico", "image/x-icon" },
            { "woff", "font/woff" },
            { "woff2", "font/woff2" },
            { "ttf", "font/ttf" },
            { "eot", "application/vnd.ms-fontobject" },
            { "mp4", "video/mp4" },
            { "webm", "video/webm" },
            { "ogg", "audio/ogg" },
            { "pdf", "application/pdf" },
            { "zip", "application/zip" },
            { "rar", "application/x-rar-compressed" },
            { "7z", "application/x-7z-compressed" },
            { "tar", "application/x-tar" },
            { "gz", "application/gzip" },
            { "bz2", "application/x-bzip2" },
            { "xls", "application/vnd.ms-excel" },
            { "xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" },
            { "doc", "application/msword" },
            { "docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document" },
            { "ppt", "application/vnd.ms-powerpoint" },
            { "pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation" },
            { "mp3", "audio/mpeg" },
            { "wav", "audio/wav" },
            { "flac", "audio/flac" },
            { "aac", "audio/aac" },
            { "avi", "video/x-msvideo" },
            { "mkv", "video/x-matroska" },
            { "mov", "video/quicktime" },
            { "wmv", "video/x-ms-wmv" },
            { "m4a", "audio/mp4" },
            { "m4v", "video/mp4" },
            { "ogv", "video/ogg" },
            { "webp", "image/webp" },
            { "avif", "image/avif" },
            { "heic", "image/heic" },
            { "heif", "image/heif" },
            { "bmp", "image/bmp" },
            { "tiff", "image/tiff" },
            { "cr2", "image/x-canon-cr2" },
            { "nef", "image/x-nikon-nef" },
            { "arw", "image/x-sony-arw" },
            { "dng", "image/x-adobe-dng" },
            { "raw", "image/x-raw" },
            { "ics", "text/calendar" },
            { "rss", "application/rss+xml" },
            { "atom", "application/atom+xml" },
            { "rtf", "application/rtf" },
            { "odt", "application/vnd.oasis.opendocument.text" },
            { "ods", "application/vnd.oasis.opendocument.spreadsheet" },
            { "odp", "application/vnd.oasis.opendocument.presentation" },
            { "kml", "application/vnd.google-earth.kml+xml" },
            { "kmz", "application/vnd.google-earth.kmz" },
            { "geojson", "application/geo+json" },
            { "csv", "text/csv" },
            { "tsv", "text/tab-separated-values" },
            { "log", "text/plain" },
            { "conf", "text/plain" },
            { "ini", "text/plain" },
            { "bat", "text/plain" },
            { "sh", "text/plain" },
            { "ps1", "text/plain" },
            { "cmd", "text/plain" },
            { "vbs", "text/plain" },
            { "py", "text/plain" },
            { "rb", "text/plain" },
            { "pl", "text/plain" },
            { "php", "text/plain" },
            { "asp", "text/plain" },
            { "aspx", "text/plain" },
            { "jsp", "text/plain" },
            { "jspx", "text/plain" },
            { "cfm", "text/plain" },
            { "cfc", "text/plain" },
            { "erb", "text/plain" },
            { "haml", "text/plain" },
            { "slim", "text/plain" },
            { "jade", "text/plain" },
            { "pug", "text/plain" },
            { "ejs", "text/plain" },
            { "mustache", "text/plain" },
            { "handlebars", "text/plain" },
            { "liquid", "text/plain" },
            { "twig", "text/plain" },
            { "smarty", "text/plain" },
            { "latte", "text/plain" },
            { "njk", "text/plain" },
            { "hbs", "text/plain" },
            { "dust", "text/plain" },
            { "dot", "text/plain" },
            { "eco", "text/plain" },
            { "tmpl", "text/plain" },
            { "tpl", "text/plain" },
            { "st", "text/plain" },
            { "ms", "text/plain" },
            { "md", "text/markdown" },
            { "markdown", "text/markdown" },
            { "rst", "text/x-rst" },
            { "adoc", "text/asciidoc" },
            { "asciidoc", "text/asciidoc" },
            { "org", "text/org" },
            { "tex", "text/x-tex" },
            { "latex", "text/x-latex" },
            { "bib", "text/x-bibtex" },
            { "cls", "text/x-latex" },
            { "sty", "text/x-latex" },
            { "dtx", "text/x-latex" },
            { "ins", "text/x-latex" },
            { "cfg", "text/plain" },
            { "config", "text/plain" },
            { "properties", "text/plain" },
            { "env", "text/plain" },
            { "yaml", "text/yaml" },
            { "yml", "text/yaml" },
            { "toml", "text/toml" },
            { "rc", "text/plain" },
            { "reg", "text/plain" },
            { "inf", "text/plain" },
            { "sys", "text/plain" },
            { "drv", "text/plain" },
            { "dll", "application/octet-stream" },
            { "exe", "application/octet-stream" },
            { "so", "application/octet-stream" },
            { "dylib", "application/octet-stream" },
            { "a", "application/octet-stream" },
            { "lib", "application/octet-stream" },
            { "o", "application/octet-stream" },
            { "obj", "application/octet-stream" },
            { "pdb", "application/octet-stream" },
            { "map", "application/octet-stream" },
            { "sym", "application/octet-stream" },
            { "dbg", "application/octet-stream" },
            { "dump", "application/octet-stream" },
            { "core", "application/octet-stream" },
            { "bin", "application/octet-stream" },
            { "dat", "application/octet-stream" },
            { "db", "application/octet-stream" },
            { "sqlite", "application/octet-stream" },
            { "mdb", "application/octet-stream" },
            { "accdb", "application/octet-stream" },
            { "frm", "application/octet-stream" },
            { "myd", "application/octet-stream" },
            { "myi", "application/octet-stream" },
            { "ibd", "application/octet-stream" },
            { "ndb", "application/octet-stream" },
            { "sql", "application/sql" },
            { "pgsql", "application/sql" },
            { "plsql", "application/sql" },
            { "t-sql", "application/sql" },
            { "mysql", "application/sql" },
            { "sqlite3", "application/sql" },
            { "db3", "application/sql" },
            { "dbf", "application/dbf" },
            { "dbase", "application/dbf" },
        };

        public static string GetContentType(string extension)
        {
            if (TypesExtesionsDict.ContainsKey(extension))
                return TypesExtesionsDict[extension];

            return "";
        }
    }

}
